"""add_farm_expense_fields

Revision ID: d832499df863
Revises: 
Create Date: 2026-04-10 15:56:53.947892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd832499df863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_expenses', sa.Column('land_name', sa.String(), nullable=True))
    op.add_column('farm_expenses', sa.Column('crop_name', sa.String(), nullable=True))
    op.add_column('farm_expenses', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('farm_expenses', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('farm_expenses', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('farm_expenses', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('farm_expenses', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('farm_expenses', sa.Column('recurring_interval', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm_expenses', 'recurring_interval')
    op.drop_column('farm_expenses', 'is_recurring')
    op.drop_column('farm_expenses', 'receipt_url')
    op.drop_column('farm_expenses', 'payment_method')
    op.drop_column('farm_expenses', 'unit')
    op.drop_column('farm_expenses', 'quantity')
    op.drop_column('farm_expenses', 'crop_name')
    op.drop_column('farm_expenses', 'land_name')
    # ### end Alembic commands ###
